In [1]:
#t-test hypothesis testing
from scipy.stats import ttest_1samp
import numpy as np

ages=np.genfromtxt("F:/ML-2019/Hypothesis/Test1.txt")
print(ages)
print("   ")
a_mean=np.mean(ages)
print("Mean :",a_mean)
ttest,pval=ttest_1samp(ages,30)
print('P-Value :',pval)

if pval<0.05:
    print('Regecting the null hypothesis')
else :
    print('Accepting the null hypothesis')
    

[10. 20. 30. 40. 23. 34. 67. 12.  3.  2. 45.]
   
Mean : 26.0
P-Value : 0.5179932500162374
Accepting the null hypothesis


In [3]:
week1=np.genfromtxt("F:/ML-2019/Hypothesis/Test2.txt",delimiter=",")
week2=np.genfromtxt("F:/ML-2019/Hypothesis/test3.txt",delimiter=",")
print("week 1")
print(week1)
print("week 2")
print(week2)
print("   ")
w1_mean=np.mean(week1)
w2_mean=np.mean(week2)
print("w1_mean :",w1_mean)
print("w2_mean :",w2_mean)
print("   ")


week 1
[ 1.  2.  3.  4.  5.  6.  7.  8.  9.  0. 11. 22. 33. 44.]
week 2
[ 2.  6. 55. 44.  7. 88. 66. 22. 44.  6.  7.  8.  9.]
   
w1_mean : 11.071428571428571
w2_mean : 28.0
   


In [4]:
w1_std=np.std(week1)
w2_std=np.std(week2)
print("week1 std :",w1_std)
print("week2 std :",w2_std)


week1 std : 12.532610523375098
week2 std : 27.185969231883625


In [6]:
from scipy.stats import ttest_ind
ttest,pval=ttest_ind(week1,week2)
print("P_val:",pval)

P_val: 0.053952866327512346


In [7]:
if pval<0.05:
    print("Regecting")
else:
    print("accepting")

accepting


In [10]:
from scipy.stats import ttest_rel
ttest,pval=ttest_rel([1,2,3,4,5],[2,3,4,5,9])
if pval<0.05:
    print("Regecting")
else:
    print("accepting")

accepting


In [ ]:
#z-score-- sample size > 30 , all are independent
from statsmodels.stats import weightstats as zstt
ztst,pval=zstt.ztest([1,2,3,4],x=[4,5,6,7],value=0,alternative='two-sided')
print("p_val :",pval)
if pval<0.05:
    print("Regecting")
else:
    print("accepting")
